export const BENEFICIARY_ADDRESS = '0x000000000000000000000000000000000000dead'; // TODO: update

const BASE_URI = 'ipfs://Qmd9WQpziLJpka1uw9EiQm4qR1GXcBJvgDTkAVth3YU3x9';
export const BOOK_COLLECTION_METADATA_URI = `${BASE_URI}/book-of-lore/collection.json`;
export const BOOK_ASSET_METADATA_URI = `${BASE_URI}/book-of-lore/book.json`;
export const PAGE_COLLECTION_METADATA_URI = `${BASE_URI}/strange-pages/collection.json`;

// For child NFTS
export const PAGE_1_METADATA_URI = `${BASE_URI}/strange-pages/assets/1.json`;
export const PAGE_2_METADATA_URI = `${BASE_URI}/strange-pages/assets/2.json`;
export const PAGE_3_METADATA_URI = `${BASE_URI}/strange-pages/assets/3.json`;
export const PAGE_4_METADATA_URI = `${BASE_URI}/strange-pages/assets/4.json`;
export const PAGE_5_METADATA_URI = `${BASE_URI}/strange-pages/assets/5.json`;
export const PAGE_6_METADATA_URI = `${BASE_URI}/strange-pages/assets/6.json`;
export const PAGE_7_METADATA_URI = `${BASE_URI}/strange-pages/assets/7.json`;
export const PAGE_8_METADATA_URI = `${BASE_URI}/strange-pages/assets/8.json`;
export const PAGE_9_METADATA_URI = `${BASE_URI}/strange-pages/assets/9.json`;
export const PAGE_10_METADATA_URI = `${BASE_URI}/strange-pages/assets/10.json`;

export const ALL_PAGES = [
  PAGE_1_METADATA_URI,
  PAGE_2_METADATA_URI,
  PAGE_3_METADATA_URI,
  PAGE_4_METADATA_URI,
  PAGE_5_METADATA_URI,
  PAGE_6_METADATA_URI,
  PAGE_7_METADATA_URI,
  PAGE_8_METADATA_URI,
  PAGE_9_METADATA_URI,
  PAGE_10_METADATA_URI,
];

// Fixed Part Metadata
export const FIXED_PART_BOOK_BASE_METADATA_URI = `${BASE_URI}/catalog/fixed/book-base.json`;
export const FIXED_PART_RIBBON_BLUE_METADATA_URI = `${BASE_URI}/catalog/fixed/ribbon-blue.json`;
export const FIXED_PART_RIBBON_GREEN_METADATA_URI = `${BASE_URI}/catalog/fixed/ribbon-green.json`;
export const FIXED_PART_RIBBON_RED_METADATA_URI = `${BASE_URI}/catalog/fixed/ribbon-red.json`;
export const FIXED_PART_RIBBON_PURPLE_METADATA_URI = `${BASE_URI}/catalog/fixed/ribbon-purple.json`;
export const FIXED_PART_RIBBON_SHADOW_METADATA_URI = `${BASE_URI}/catalog/fixed/ribbon-shadow.json`;
export const FIXED_PART_RUNE_1A_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-1a.json`;
export const FIXED_PART_RUNE_1B_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-1b.json`;
export const FIXED_PART_RUNE_1C_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-1c.json`;
export const FIXED_PART_RUNE_2A_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-2a.json`;
export const FIXED_PART_RUNE_2B_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-2b.json`;
export const FIXED_PART_RUNE_2C_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-2c.json`;
export const FIXED_PART_RUNE_3A_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-3a.json`;
export const FIXED_PART_RUNE_3B_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-3b.json`;
export const FIXED_PART_RUNE_3C_METADATA_URI = `${BASE_URI}/catalog/fixed/rune-3c.json`;
export const FIXED_PART_TREE_BLUE_METADATA_URI = `${BASE_URI}/catalog/fixed/tree-blue.json`;
export const FIXED_PART_TREE_BRIGHT_METADATA_URI = `${BASE_URI}/catalog/fixed/tree-bright.json`;
export const FIXED_PART_TREE_DARK_METADATA_URI = `${BASE_URI}/catalog/fixed/tree-dark.json`;

export const ALL_FIXED_PARTS = [
  FIXED_PART_BOOK_BASE_METADATA_URI,
  FIXED_PART_RIBBON_BLUE_METADATA_URI,
  FIXED_PART_RIBBON_GREEN_METADATA_URI,
  FIXED_PART_RIBBON_RED_METADATA_URI,
  FIXED_PART_RIBBON_PURPLE_METADATA_URI,
  FIXED_PART_RIBBON_SHADOW_METADATA_URI,
  FIXED_PART_RUNE_1A_METADATA_URI,
  FIXED_PART_RUNE_1B_METADATA_URI,
  FIXED_PART_RUNE_1C_METADATA_URI,
  FIXED_PART_RUNE_2A_METADATA_URI,
  FIXED_PART_RUNE_2B_METADATA_URI,
  FIXED_PART_RUNE_2C_METADATA_URI,
  FIXED_PART_RUNE_3A_METADATA_URI,
  FIXED_PART_RUNE_3B_METADATA_URI,
  FIXED_PART_RUNE_3C_METADATA_URI,
  FIXED_PART_TREE_BLUE_METADATA_URI,
  FIXED_PART_TREE_BRIGHT_METADATA_URI,
  FIXED_PART_TREE_DARK_METADATA_URI,
];

// Slot Part Metadata
export const SLOT_PART_PAGE_1_METADATA_URI = `${BASE_URI}/catalog/slot/page-1.json`;
export const SLOT_PART_PAGE_2_METADATA_URI = `${BASE_URI}/catalog/slot/page-2.json`;
export const SLOT_PART_PAGE_3_METADATA_URI = `${BASE_URI}/catalog/slot/page-3.json`;
export const SLOT_PART_PAGE_4_METADATA_URI = `${BASE_URI}/catalog/slot/page-4.json`;
export const SLOT_PART_PAGE_5_METADATA_URI = `${BASE_URI}/catalog/slot/page-5.json`;
export const SLOT_PART_PAGE_6_METADATA_URI = `${BASE_URI}/catalog/slot/page-6.json`;
export const SLOT_PART_PAGE_7_METADATA_URI = `${BASE_URI}/catalog/slot/page-7.json`;
export const SLOT_PART_PAGE_8_METADATA_URI = `${BASE_URI}/catalog/slot/page-8.json`;
export const SLOT_PART_PAGE_9_METADATA_URI = `${BASE_URI}/catalog/slot/page-9.json`;
export const SLOT_PART_PAGE_10_METADATA_URI = `${BASE_URI}/catalog/slot/page-10.json`;

export const ALL_SLOT_PARTS = [
  SLOT_PART_PAGE_1_METADATA_URI,
  SLOT_PART_PAGE_2_METADATA_URI,
  SLOT_PART_PAGE_3_METADATA_URI,
  SLOT_PART_PAGE_4_METADATA_URI,
  SLOT_PART_PAGE_5_METADATA_URI,
  SLOT_PART_PAGE_6_METADATA_URI,
  SLOT_PART_PAGE_7_METADATA_URI,
  SLOT_PART_PAGE_8_METADATA_URI,
  SLOT_PART_PAGE_9_METADATA_URI,
  SLOT_PART_PAGE_10_METADATA_URI,
];

// Z-Indices
export const FIXED_PART_BOOK_BASE_Z_INDEX = 1n;
export const FIXED_PART_RIBBON_BLUE_Z_INDEX = 2n;
export const FIXED_PART_RIBBON_GREEN_Z_INDEX = 2n;
export const FIXED_PART_RIBBON_RED_Z_INDEX = 2n;
export const FIXED_PART_RIBBON_PURPLE_Z_INDEX = 2n;
export const FIXED_PART_RIBBON_SHADOW_Z_INDEX = 2n;
export const FIXED_PART_RUNE_1B_Z_INDEX = 4n;
export const FIXED_PART_RUNE_1A_Z_INDEX = 4n;
export const FIXED_PART_RUNE_1C_Z_INDEX = 4n;
export const FIXED_PART_RUNE_2A_Z_INDEX = 5n;
export const FIXED_PART_RUNE_2B_Z_INDEX = 5n;
export const FIXED_PART_RUNE_2C_Z_INDEX = 5n;
export const FIXED_PART_RUNE_3A_Z_INDEX = 6n;
export const FIXED_PART_RUNE_3B_Z_INDEX = 6n;
export const FIXED_PART_RUNE_3C_Z_INDEX = 6n;
export const FIXED_PART_TREE_BLUE_Z_INDEX = 3n;
export const FIXED_PART_TREE_BRIGHT_Z_INDEX = 3n;
export const FIXED_PART_TREE_DARK_Z_INDEX = 3n;

export const ALL_FIXED_PARTS_Z_INDICES = [
  FIXED_PART_BOOK_BASE_Z_INDEX,
  FIXED_PART_RIBBON_BLUE_Z_INDEX,
  FIXED_PART_RIBBON_GREEN_Z_INDEX,
  FIXED_PART_RIBBON_RED_Z_INDEX,
  FIXED_PART_RIBBON_PURPLE_Z_INDEX,
  FIXED_PART_RIBBON_SHADOW_Z_INDEX,
  FIXED_PART_RUNE_1A_Z_INDEX,
  FIXED_PART_RUNE_1B_Z_INDEX,
  FIXED_PART_RUNE_1C_Z_INDEX,
  FIXED_PART_RUNE_2A_Z_INDEX,
  FIXED_PART_RUNE_2B_Z_INDEX,
  FIXED_PART_RUNE_2C_Z_INDEX,
  FIXED_PART_RUNE_3A_Z_INDEX,
  FIXED_PART_RUNE_3B_Z_INDEX,
  FIXED_PART_RUNE_3C_Z_INDEX,
  FIXED_PART_TREE_BLUE_Z_INDEX,
  FIXED_PART_TREE_BRIGHT_Z_INDEX,
  FIXED_PART_TREE_DARK_Z_INDEX,
];

export const SLOT_PART_PAGE_1_Z_INDEX = 7n;
export const SLOT_PART_PAGE_2_Z_INDEX = 8n;
export const SLOT_PART_PAGE_3_Z_INDEX = 9n;
export const SLOT_PART_PAGE_4_Z_INDEX = 10n;
export const SLOT_PART_PAGE_5_Z_INDEX = 11n;
export const SLOT_PART_PAGE_6_Z_INDEX = 12n;
export const SLOT_PART_PAGE_7_Z_INDEX = 13n;
export const SLOT_PART_PAGE_8_Z_INDEX = 14n;
export const SLOT_PART_PAGE_9_Z_INDEX = 15n;
export const SLOT_PART_PAGE_10_Z_INDEX = 16n;

export const ALL_SLOT_PARTS_Z_INDICES = [
  SLOT_PART_PAGE_1_Z_INDEX,
  SLOT_PART_PAGE_2_Z_INDEX,
  SLOT_PART_PAGE_3_Z_INDEX,
  SLOT_PART_PAGE_4_Z_INDEX,
  SLOT_PART_PAGE_5_Z_INDEX,
  SLOT_PART_PAGE_6_Z_INDEX,
  SLOT_PART_PAGE_7_Z_INDEX,
  SLOT_PART_PAGE_8_Z_INDEX,
  SLOT_PART_PAGE_9_Z_INDEX,
  SLOT_PART_PAGE_10_Z_INDEX,
];

// Part IDs
export const FIXED_PART_BOOK_BASE_PART_ID = 1n;
export const FIXED_PART_RIBBON_BLUE_PART_ID = 6n;
export const FIXED_PART_RIBBON_GREEN_PART_ID = 7n;
export const FIXED_PART_RIBBON_RED_PART_ID = 8n;
export const FIXED_PART_RIBBON_PURPLE_PART_ID = 9n;
export const FIXED_PART_RIBBON_SHADOW_PART_ID = 10n;
export const FIXED_PART_RUNE_1A_PART_ID = 11n;
export const FIXED_PART_RUNE_1B_PART_ID = 12n;
export const FIXED_PART_RUNE_1C_PART_ID = 13n;
export const FIXED_PART_RUNE_2A_PART_ID = 14n;
export const FIXED_PART_RUNE_2B_PART_ID = 15n;
export const FIXED_PART_RUNE_2C_PART_ID = 16n;
export const FIXED_PART_RUNE_3A_PART_ID = 17n;
export const FIXED_PART_RUNE_3B_PART_ID = 18n;
export const FIXED_PART_RUNE_3C_PART_ID = 19n;
export const FIXED_PART_TREE_BLUE_PART_ID = 20n;
export const FIXED_PART_TREE_BRIGHT_PART_ID = 21n;
export const FIXED_PART_TREE_DARK_PART_ID = 22n;

export const ALL_FIXED_PARTS_IDS = [
  FIXED_PART_BOOK_BASE_PART_ID,
  FIXED_PART_RIBBON_BLUE_PART_ID,
  FIXED_PART_RIBBON_GREEN_PART_ID,
  FIXED_PART_RIBBON_RED_PART_ID,
  FIXED_PART_RIBBON_PURPLE_PART_ID,
  FIXED_PART_RIBBON_SHADOW_PART_ID,
  FIXED_PART_RUNE_1A_PART_ID,
  FIXED_PART_RUNE_1B_PART_ID,
  FIXED_PART_RUNE_1C_PART_ID,
  FIXED_PART_RUNE_2A_PART_ID,
  FIXED_PART_RUNE_2B_PART_ID,
  FIXED_PART_RUNE_2C_PART_ID,
  FIXED_PART_RUNE_3A_PART_ID,
  FIXED_PART_RUNE_3B_PART_ID,
  FIXED_PART_RUNE_3C_PART_ID,
  FIXED_PART_TREE_BLUE_PART_ID,
  FIXED_PART_TREE_BRIGHT_PART_ID,
  FIXED_PART_TREE_DARK_PART_ID,
];

export const SLOT_PART_PAGE_1_SLOT_ID = 1001n;
export const SLOT_PART_PAGE_2_SLOT_ID = 1002n;
export const SLOT_PART_PAGE_3_SLOT_ID = 1003n;
export const SLOT_PART_PAGE_4_SLOT_ID = 1004n;
export const SLOT_PART_PAGE_5_SLOT_ID = 1005n;
export const SLOT_PART_PAGE_6_SLOT_ID = 1006n;
export const SLOT_PART_PAGE_7_SLOT_ID = 1007n;
export const SLOT_PART_PAGE_8_SLOT_ID = 1008n;
export const SLOT_PART_PAGE_9_SLOT_ID = 1009n;
export const SLOT_PART_PAGE_10_SLOT_ID = 1010n;

export const ALL_SLOT_PARTS_IDS = [
  SLOT_PART_PAGE_1_SLOT_ID,
  SLOT_PART_PAGE_2_SLOT_ID,
  SLOT_PART_PAGE_3_SLOT_ID,
  SLOT_PART_PAGE_4_SLOT_ID,
  SLOT_PART_PAGE_5_SLOT_ID,
  SLOT_PART_PAGE_6_SLOT_ID,
  SLOT_PART_PAGE_7_SLOT_ID,
  SLOT_PART_PAGE_8_SLOT_ID,
  SLOT_PART_PAGE_9_SLOT_ID,
  SLOT_PART_PAGE_10_SLOT_ID,
];

export const CATALOG_METADATA_URI = `${BASE_URI}/catalog/catalog.json`;
export const CATALOG_TYPE = 'image/png';

export const PART_TYPE_SLOT = 1n;
export const PART_TYPE_FIXED = 2n;
